import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import Headerone from "./component/Headerone";
import Hero from "./component/Hero";
import Footer from "./component/Footer";
import EditorPick from "./component/EditorPick";
import BestProduct from "./component/BestProduct";
import CaroueslPost from "./component/CaroueslPost";
import FeaturedPost from "./component/FeaturedPost";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Headerone/>
        <Header/>
         <Hero/>
         <EditorPick/>
         <BestProduct/>
         <CaroueslPost/>
         <FeaturedPost/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
